NOTEA/Controllers/HomeController.cs, NOTEA/Models/ConspectModel.cs, NOTEA/Views/Home/CreateConspects.cshtml
Added fields that can input date, name and text into conspectus model object. Added two simple constructors for ConspectModel that may need to be removed later. CreateConspect function also creates a ConspectModel object that may be used for futher manipulation.
=> Rudimentary conspect creation view

NOTEA/Controllers/HomeController.cs, NOTEA/Models/DataService.cs, NOTEA/Test.txt
Kind of made the code work. Leaving it for tomorrow's great expeditions. Wishing success for our kind soldiers
=> Combining code to make it work

NOTEA/Controllers/HomeController.cs, NOTEA/Controllers/MessageControler.cs, NOTEA/NOTEA.csproj, NOTEA/Test.txt, NOTEA/Views/Home/CreateConspects.cshtml, NOTEA/Views/Home/PopUpMessage.cshtml, NOTEA/Views/Shared/_Layout.cshtml
=> Adding pop-up message branch

NOTEA/Models/DataService.cs, NOTEA/Test.txt
Some name changes, and clevererer code
=> Minor refactoring

NOTEA/Controllers/HomeController.cs, NOTEA/Models/DataService.cs, NOTEA/Models/IDataService.cs, NOTEA/Program.cs
Added data service interface, fixed bug in code and removed unnecessary Save action from home controller.
=> Data service interface, minor code improvements

NOTEA/Conspects/Fizika.txt, NOTEA/Controllers/HomeController.cs, NOTEA/Models/DataService.cs, NOTEA/Models/FileHandlerModel.cs, NOTEA/Views/Home/CreateConspects.cshtml, NOTEA/Views/Home/UploadConspect.cshtml, NOTEA/Views/Shared/_Layout.cshtml
Added ability to upload your own file to conspects folder as well as a minor code refactoring.
=> File conspect upload added

NOTEA/Conspects/Istorija 2.txt, NOTEA/Conspects/Matematika 1 .txt, NOTEA/Conspects/Matematika 1.txt, NOTEA/Conspects/Matematika.txt, NOTEA/Controllers/HomeController.cs, NOTEA/FileNames.txt, NOTEA/Models/DataService.cs, NOTEA/Models/FileNameListModel.cs, NOTEA/Models/FileNameModel.cs, NOTEA/Models/IDataService.cs, NOTEA/Views/Home/ConspectList.cshtml, NOTEA/Views/Shared/_Layout.cshtml
Please check if everything is okay
=> View of Conspect List added

NOTEA/Controllers/HomeController.cs, NOTEA/Models/DataService.cs, NOTEA/Models/IDataService.cs
=> Hotfix for SaveConspect

NOTEA/Conspects/Fizika.txt, NOTEA/Conspects/du.txt, NOTEA/Conspects/keturi.txt, NOTEA/Controllers/HomeController.cs, NOTEA/FileNames.txt, NOTEA/Models/DataService.cs
=> Minor changes

NOTEA/Conspects/Default.txt, NOTEA/Conspects/Fizika.txt, NOTEA/Conspects/Istorija.txt, NOTEA/Controllers/ConspectController.cs, NOTEA/Models/ConspectModel.cs
Fulfilled second requirement by using class property functionality to prevent setting the date that corresponds to the future date.
=> Added class property usage

NOTEA/Views/Conspect/ViewConspect.cshtml
=> Adding minor changes in ViewConspect

NOTEA/Conspects/Tezė.txt, NOTEA/Controllers/ConspectController.cs, NOTEA/Models/ConspectModel.cs, NOTEA/Views/Conspect/ConspectList.cshtml
=> Adding Sort

NOTEA/Conspects/Naujas.txt, NOTEA/Conspects/PSI.txt, NOTEA/Controllers/ConspectController.cs, NOTEA/Models/ConspectModel.cs, NOTEA/Views/Conspect/CreateConspects.cshtml
=> Adding enum

NOTEA/Controllers/ConspectController.cs, NOTEA/Models/ConspectModel.cs, NOTEA/Views/Conspect/CreateConspects.cshtml
=> Changing ConspectType to ConspectSemester

NOTEA/Controllers/ConspectController.cs, NOTEA/Models/ConspectListModel.cs, NOTEA/Views/Conspect/ConspectList.cshtml
=> Adding search bar

NOTEA/Conspects/Brr.txt, NOTEA/Conspects/Su semestru.txt, NOTEA/Conspects/batai.txt, NOTEA/Conspects/tikrai su semestru.txt, NOTEA/Conspects/txt.txt, NOTEA/Models/ConspectModel.cs
Fixed file format in other merged conspects. Also fixed one merge bug.
=> Fixed old conspects

NOTEA/Controllers/UserController.cs, NOTEA/Models/UserListModel.cs, NOTEA/Models/UserModel.cs, NOTEA/NOTEA.csproj, NOTEA/Users/Users.txt, NOTEA/Views/Shared/_Layout.cshtml, NOTEA/Views/User/SignIn.cshtml
=> Adding sign in

NOTEA.sln, NOTEA/Conspects/Kamuoliukas.txt, NOTEA/Conspects/Kas skaitys.txt, NOTEA/Controllers/ConspectController.cs, NOTEA/Models/NameValidator.cs, NOTEA/Views/Conspect/ConspectList.cshtml, NOTEA/Views/Conspect/CreateConspects.cshtml, NOTEA/Views/Conspect/UploadConspect.cshtml
Please, check it out, I'm begging you...
=> adding pop-up windows

NOTEA/Controllers/ConspectController.cs, NOTEA/Views/Conspect/ConspectList.cshtml
Fixed too long of a conspect causing a html error or about blank pages.
=> Long conspect fix

NOTEA/Controllers/UserController.cs, NOTEA/Views/Conspect/ConspectList.cshtml, NOTEA/Views/Conspect/CreateConspects.cshtml, NOTEA/Views/Conspect/UploadConspect.cshtml, NOTEA/Views/Conspect/ViewConspect.cshtml, NOTEA/Views/Home/Index.cshtml, NOTEA/Views/Home/Privacy.cshtml, NOTEA/Views/Shared/_Layout.cshtml, NOTEA/Views/User/LogIn.cshtml, NOTEA/Views/User/SignIn.cshtml
Adding automatic log out after being not active for 2 hours
=> Adding automatic log out

NOTEA/Conspects/Pasakele.txt, NOTEA/Controllers/ConspectController.cs, NOTEA/Extentions/EnumExtention.cs, NOTEA/Views/Conspect/ConspectList.cshtml, NOTEA/Views/Conspect/ViewConspect.cshtml, NOTEA/Views/Home/Privacy.cshtml
Changing the display of the enums and fixing it in the linq
=> Fixing enums

NOTEA/Views/User/LogIn.cshtml
=> Pop up fix

NOTEA/Controllers/ConspectController.cs, NOTEA/Models/ConspectModels/ConspectModel.cs, NOTEA/Models/UserModels/UserModel.cs, NOTEA/Models/Utilities/SelectionBuilder.cs
Fixed a bug when searching for semester
=> Linq bugfix

NOTEA/Views/Conspect/ConspectList.cshtml
When in conspect list, hovering over table header or conspect name buttons now adds some highlighting.
=> Highlight of buttons

NOTEA/Controllers/UserController.cs, NOTEA/Models/UserModels/IOnlineUserList.cs, NOTEA/Models/UserModels/OnlineUserList.cs, NOTEA/Program.cs, NOTEA/Views/User/UserList.cshtml
=> Made the static class singleton

NOTEA/Controllers/ConspectController.cs, NOTEA/Database/DatabaseContext.cs, NOTEA/Database/IDatabaseContext.cs, NOTEA/Program.cs, NOTEA/Repositories/GenericRepositories/GenericRepository.cs, NOTEA/Repositories/UserRepositories/UserRepository.cs
Self-explanatory. Please ignore branch name
=> Database context interface

NOTEA/Controllers/ConspectController.cs, NOTEA/Controllers/UserController.cs, NOTEA/Views/Conspect/ConspectList.cshtml
Quick fix for crashing (if user is not logged in)
=> Quick fix for crashing settings and conspect list
